package com.emos.notifications.application;
import com.emos.attentionfollowthrough.application.AttentionQueryService;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.stereotype.Service;import java.time.*;import java.util.*;
@Service @ConditionalOnProperty(name="emos.email.enabled",havingValue="true")
public class DailyDigestService{
 private final AttentionQueryService attention;private final EmailPort email;private final DigestDeliveryStore deliveries;private final String recipient;private final String baseUrl;private final Clock clock;
 public DailyDigestService(AttentionQueryService a,EmailPort e,DigestDeliveryStore d,@Value("${emos.email.manager-recipient:}") String r,@Value("${emos.base-url:http://localhost:5173}") String b,Clock c){attention=a;email=e;deliveries=d;recipient=r;baseUrl=b;clock=c;}
 public DigestResult sendFor(LocalDate date){var items=attention.findOpen().stream().sorted(Comparator.comparing(AttentionQueryService.AttentionSummary::deadline).thenComparing(AttentionQueryService.AttentionSummary::reason)).toList();if(items.isEmpty()||deliveries.wasSent(date,recipient))return new DigestResult(false,items.size());var text=new StringBuilder("EMOS attention\n");var html=new StringBuilder("<h1>EMOS attention</h1><p><a href=\"").append(baseUrl).append("/today?attention=open\">Open dashboard</a></p><ol>");for(var item:items){text.append(item.reason()).append(" ").append(baseUrl).append("/cases/").append(item.caseId().value()).append("\n");html.append("<li><a href=\"").append(baseUrl).append("/cases/").append(item.caseId().value()).append("\">").append(escape(item.reason())).append("</a></li>");}html.append("</ol>");try{email.send(recipient,"EMOS attention for "+date,text.toString(),html.toString());deliveries.sent(date,recipient,clock.instant());return new DigestResult(true,items.size());}catch(RuntimeException failure){deliveries.failed(date,recipient,clock.instant(),"Email delivery failed");throw failure;}}
 private static String escape(String value){return value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
}
