package com.emos.notifications.application;import com.emos.attentionfollowthrough.application.AttentionQueryService;import com.emos.attentionfollowthrough.domain.ObligationId;import com.emos.operationalobservation.domain.OperationalCaseId;import org.junit.jupiter.api.Test;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;
class DailyDigestServiceTest{
 @Test void sends_once_in_dashboard_order_with_filtered_links(){var email=new FakeEmail();var store=new MemoryStore();var attention=query(List.of(item("B",2),item("A",1)));var service=new DailyDigestService(attention,email,store,"manager@example.com","http://localhost:5173",Clock.systemUTC());var date=LocalDate.now(Clock.systemUTC());assertThat(service.sendFor(date).sent()).isTrue();assertThat(service.sendFor(date).sent()).isFalse();assertThat(email.html).contains("/today?attention=open");assertThat(email.html.indexOf("A")).isLessThan(email.html.indexOf("B"));}
 @Test void sends_nothing_when_empty_and_retries_after_failure(){var email=new FakeEmail();email.fail=true;var store=new MemoryStore();var service=new DailyDigestService(query(List.of(item("A",1))),email,store,"manager@example.com","http://localhost",Clock.systemUTC());assertThatThrownBy(()->service.sendFor(LocalDate.now())).isInstanceOf(RuntimeException.class);email.fail=false;assertThat(service.sendFor(LocalDate.now()).sent()).isTrue();assertThat(new DailyDigestService(query(List.of()),email,new MemoryStore(),"manager@example.com","http://localhost",Clock.systemUTC()).sendFor(LocalDate.now()).sent()).isFalse();}
 static AttentionQueryService.AttentionSummary item(String reason,int hours){return new AttentionQueryService.AttentionSummary(UUID.randomUUID(),new ObligationId(UUID.randomUUID()),new OperationalCaseId(UUID.randomUUID()),reason,Instant.now().plusSeconds(hours*3600L),Instant.now());}
 static AttentionQueryService query(List<AttentionQueryService.AttentionSummary> items){return new AttentionQueryService(){public List<AttentionSummary> findOpen(){return items;}public List<PendingObligationSummary> findPending(){return List.of();}};}
 static class FakeEmail implements EmailPort{boolean fail;String html;public void send(String to,String subject,String text,String html){if(fail)throw new RuntimeException("smtp");this.html=html;}}
 static class MemoryStore implements DigestDeliveryStore{Set<String> sent=new HashSet<>();public boolean wasSent(LocalDate d,String r){return sent.contains(d+ r);}public void sent(LocalDate d,String r,Instant at){sent.add(d+r);}public void failed(LocalDate d,String r,Instant at,String message){}}
}
